### ISSUE TITLE
ОТ комьюнити Nukepowered

### ISSUE THREAD

**Issue by 6MaXXaM6** [TheDarkDnKTv/vue3-ts-classes-test#1]
От всего комьюнити Nukepowered поздравляем с освоением православного фреймворка жаль конечно не на ёптаскрипт ну ладно, но ты перейдя в фронтенд о нас не забывай, мы раз в год заходим на сервак)

**Comment by TheDarkDnKTv** [comment]
Спасибо. По мере возможности занимаюсь проектом.
P.S для связи есть дискорд или группа в вк (ссылка на сайте)
